# Generated by Django 5.1.3 on 2024-11-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id_can', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre_can', models.CharField(blank=True, max_length=100)),
                ('apellido_can', models.CharField(blank=True, max_length=100)),
                ('email_can', models.CharField(blank=True, max_length=100)),
                ('telefono_can', models.CharField(blank=True, max_length=10)),
                ('fecha_nac_can', models.DateField(blank=True, null=True)),
                ('genero_can', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vacantes',
            fields=[
                ('id_vac', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nom_vac', models.CharField(max_length=30)),
                ('id_can', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratacion.candidatos')),
            ],
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id_loc', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre_loc', models.CharField(max_length=50)),
                ('direccion_loc', models.CharField(max_length=100)),
                ('id_vac', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratacion.vacantes')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_con', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('fecha_ini_con', models.DateField()),
                ('fecha_fin_con', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_can', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratacion.candidatos')),
                ('id_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratacion.locales')),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratacion.vacantes')),
            ],
        ),
    ]
